### ISSUE TITLE
Error when running the server with --dev mode

### ISSUE THREAD

**Issue by PCatinean** [OCA/website-cms#3]
If I run the server in --dev mode I get this traceback:

``ParseError: "Invalid view definition

Error details:
'NoneType' object is not iterable
None" while parsing None:24, near``

```
<t name="Page default" t-name="website_cms.page_default">
    <t t-call="website.layout">
      <div class="container">
        <t t-call="website_cms.page_default_content">
          <t t-set="show_name" t-value="False"/>
          <t t-set="show_description" t-value="False"/>
        </t>
      </div>
    </t>
  </t>
```

**Comment by pedrobaeza** [comment]
The module is not yet merged, so better to comment it in the PR itself.

**Comment by PCatinean** [comment]
Oops, added it here by mistake. Sorry.
