### ISSUE TITLE
[11.0]Conflict between cms_form and website_sale modules

### ISSUE THREAD

**Issue by HviorForgeFlow** [OCA/website-cms#42]
![image](https://user-images.githubusercontent.com/32061121/36544007-a8673c36-17e5-11e8-961d-fbebf306046c.png)

http://3317260-11-0-16fa16.runbot2.odoo-community.org/partners

**Comment by JordiBForgeFlow** [comment]
@simahawk have you faced this issue? We want to contribute as much as possible to this project!

**Comment by simahawk** [comment]
@jbeficent sorry, I missed this issue :/
It's due to this https://github.com/odoo/odoo/pull/22384 ... maybe you can help me push on them ;)

**Comment by simahawk** [comment]
note that I've already included a quick fix here https://github.com/OCA/website-cms/commit/afef2203869e1a1a70fcdc18da117482a4df3deb

I have to check if it's fine to use the emtpy recordset solution but I expect it to be broken as I rely on main_object=None to state when you have or don't have any record at all.

**Comment by JordiBForgeFlow** [comment]
Thanks! We'll push as well.

**Comment by simahawk** [comment]
@jbeficent BTW what do you need / try to achieve? Let me know if you need more help ;)

**Comment by JordiBForgeFlow** [comment]
Our end goal is to publish products or even a bill of materials, not necessarily related to the store, but for people to be able to view, for example, what components make up for a finished product. We need that information to be available to the general public, not only to registered users.

Your work is amazing. Thank you very much for sharing it!

**Comment by simahawk** [comment]
@jbeficent @hveficent still an issue here?

**Comment by HviorForgeFlow** [comment]
It seems not! Thank for fixes, closing
