### ISSUE TITLE
[cms_form] Translation of cms_form

### ISSUE THREAD

**Issue by ecino** [OCA/website-cms#68]
I try to make a form using the _form_fieldsets for displaying sections. Here is a preview of the code :
```
_form_fieldsets = [
            {
                'id': 'sport',
                'title': _('Your sport profile'),
                'description': '',
                'fields': ['sport_discipline_id', 'sport_level',
                           'sport_level_description',
                           'event_id']
            },
```
The section titles are always in English, although in the navigator I put the FR url of the website. Field labels are translated correctly. Is it possible at all to have translations for the form titles?

**Comment by simahawk** [comment]
@ecino I think is just a documentation issue on my side. If you want translations to work you have to load the string at runtime not on server start. Meaning:
```python
@property
def _form_fieldsets(self):
[...]
```
in this way is evaluated on the fly. See also `form_title` which uses the same approach.

Do it like this for now, I'll improve the implementation.

Thanks for reporting BTW! :wink:

**Comment by ecino** [comment]
Ok, thanks for the tip! Very useful module by the way ;)
