### ISSUE TITLE
transifex test fails

### ISSUE THREAD

**Issue by simahawk** [OCA/website-cms#7]
https://travis-ci.org/OCA/website-cms/jobs/193012401#L273

@pedrobaeza can you help w/ this?

**Comment by simahawk** [comment]
Note to myself: RTFM https://github.com/OCA/maintainer-tools/wiki/Activate-Transifex

**Comment by moylop260** [comment]
Hello @simahawk It was fixed?

**Comment by simahawk** [comment]
@moylop260 nope, I just found the docs and posted here to remember what to check.
I think we just need to adjust this part https://github.com/OCA/website-cms/blob/9.0/.travis.yml#L34
If you have time... can you kindly have a look at this? :smile:

**Comment by moylop260** [comment]
@pedrobaeza @max3903 
I didn't see the token for transifex of website-cms:
https://github.com/OCA/maintainer-quality-tools/issues/194#issue-79502151

Could you generate it, please?

**Comment by pedrobaeza** [comment]
Fixed already
