### ISSUE TITLE
Fix 11.0 build after stricter rules for RST landed on MQT

### ISSUE THREAD

**Issue by simahawk** [OCA/website-cms#70]

**Comment by simahawk** [comment]
![image](https://user-images.githubusercontent.com/347149/41336947-0a295eea-6eee-11e8-9394-c66846745393.png)

@sbidoul what if I want to group items together by type (fix, imp, doc, etc)? Seems impossible here :(
See https://github.com/OCA/website-cms/blob/11.0/cms_form/CHANGES.rst

**Comment by sbidoul** [comment]
@simahawk this kind of errors bother me too. I've not had time to go to the bottom of that issue yet.

First thing to check is if pypi.org's [readme_renderer](https://pypi.org/project/readme_renderer/) chokes on the same problem or is more resilient.

**Comment by simahawk** [comment]
readme_renderer fails even before:
```bash
running check
warning: check: missing required meta-data: url

error: Please correct your package.
```
I ran this into setup/cms_form, but I guess I have to run it manually against RST file only (seems there's no api).

**Comment by simahawk** [comment]
dammit, my bad! I switched terminal tab and the virtualenv was not activated there :sweat_smile: 
But now I get:
```bash
$ python setup.py check -r -s
fatal: Path 'cms_form/__openerp__.py' does not exist in '2cbd862'
fatal: Path 'cms_form/__openerp__.py' does not exist in '5a3e36f'
fatal: Path 'cms_form/__openerp__.py' does not exist in 'a7b340a'
fatal: Path 'cms_form/__openerp__.py' does not exist in '7fd8895'
fatal: Path 'cms_form/__openerp__.py' does not exist in '64b90d7'
running check
warning: Check: missing required meta-data: url

The project's long description is valid RST.
error: Please correct your package.
```

**Comment by simahawk** [comment]
nevertheless, [rstcheck](https://pypi.org/project/rstcheck/) gives me a proper output on single files:
```bash
$ rstcheck odoo/external-src/website-cms/cms_form/CHANGES.rst 
odoo/external-src/website-cms/cms_form/CHANGES.rst:28: (INFO/1) Duplicate implicit target name: "improvements".
```

**Comment by sbidoul** [comment]
So this would mean that our lint check is stricter that what is required by pypi?

**Comment by simahawk** [comment]
the issue is related to conversion to HTML whereas the tool will try to assign links to sections and since the names are duplicated the resulting IDs makes impossible to have unique hashes for links.

I tried to assign specific IDs to them but no luck. 

Now, since having links is not important and is not important to have entries like "fixes", "docs", etc, grouped in subheading, I'm moving them to simple bold paragraphs.

**Comment by pedrobaeza** [comment]
The solution is to put `__` instead of `_`in the links

**Comment by simahawk** [comment]
@pedrobaeza I read that but here's not about links, is about headings converted to links ;)
This is the change I made https://github.com/OCA/website-cms/commit/73055e5f6e3a1a7f7e3d5e6e4049b5463e26dbf3

**Comment by pedrobaeza** [comment]
Ah, I see, look if this helps:

https://stackoverflow.com/questions/39717529/duplicate-implicit-target-name-how-to-use-a-subtitle-name-more-than-once

**Comment by simahawk** [comment]
that's what I tried (I stumbled upon the same post :wink:): does not work tho :(
BTW build seems green now \o/
