### ISSUE TITLE
[10.0][cms_form] ImageWidget not working?

### ISSUE THREAD

**Issue by ecino** [OCA/website-cms#73]
Hello,
I'm trying to add an image upload field in a website form. The field correctly displays in the form and I can choose a picture from my computer. However when I submit the form, the image data is not passed to the controller.

If I inspect the request that is sent to Odoo, the image is not present in the POST data. Every other fields are there. Is there a potential bug or am I not understanding how to use it? Here is some previews of my code:

```
ambassador_picture_1 = fields.Binary('Profile picture')
@property
def form_widgets(self):
 res = super(RegistrationForm, self).form_widgets
   res.update({
                'ambassador_picture_1': 'cms.form.widget.image',
            })
   return res
```

**Comment by ecino** [comment]
One another issue that I could just correct by changing css rule. The binary widget is very huge in the form due to css rule of height 100%. I overrided with that and it worked better :
```
.form-field input[type=file].form-control {
    height: initial !important;
}
```

**Comment by simahawk** [comment]
> One another issue that I could just correct by changing css rule. The binary widget is very huge in the form due to css rule of height 100%. I overrided with that and it worked better 

this is because you must set the height you prefer on the parent.

Regarding the main issue: what do you get in the request [here](https://github.com/OCA/website-cms/blob/10.0/cms_form/models/cms_form_mixin.py#L358)?

~BTW is it v11?~ v10 :stuck_out_tongue:

**Comment by ecino** [comment]
I didn't receive the picture in the request parameters but I just found why: I included the form in a modal popup inside a page template. In order to get the result inside the modal and avoid rendering the whole page after submission, I included javascript to send the request. My javascript was not sending the request properly and that was my issue.

Thanks for your help, I close the issue now.
