### ISSUE TITLE
select2widgets: python domain not evaluated properly for JS

### ISSUE THREAD

**Issue by TelmoSenseFly** [OCA/website-cms#89]
In the method ```website-cms/cms_form/static/src/js/select2widgets.js``` when I pass the domain as a std list of tuple, $input.data('domain') is not properly evaluated. At the end the result is that no domain is applied.

I end up representing the domain with a string like the example:
 ``` 
            domain = '[' \
                     '["product_reseller_type", "in", ["srv", "srvextd"]], ' \
                     '["sale_ok", "=", true], ["validated", "=", true]' \
                     ']'
```

**Comment by simahawk** [comment]
tnx for reporting! :+1:
