### ISSUE TITLE
Are AbstractModels a good choice for CMS forms?

### ISSUE THREAD

**Issue by ecino** [OCA/website-cms#98]
We developed a few website forms using the form classes provided with the module cms_form. I'm not sure if it's our implementation that is wrong or if it's due to the fact that forms are using AbstractModel as base class, but we ran into the issue that our form values are being lost when we do some operations during the _process_post method.

For instance let's say we have a form with the field `partner_id = fields.Many2one` inside it. We inherit method `form_before_create` method to do some operations inside. We do for instance `self.partner_id.write({...})`. It happens to us that after some of these operations, we lose the data on our object. After performing the write, `self.partner_id` no longer contains anything and the whole form object is empty.

To circumvent this, we perform our operations in asynchronous jobs using the queue_job module. But we were wondering: is this our implementation that is bad, or would it be less prone to such unexpected behaviours if the Form models would extend "TransientModel" instead of "AbstractModel" for instance?

Thanks in advance for your help on this issue.

**Comment by simahawk** [comment]
@ecino that's wrong. The main record of the form is not the form, is the record it self.
It stays in `self.main_object`.

If you describe your use case I can help find you the way the suits you...

**Comment by ecino** [comment]
So that means a form should always relate to an object? It removes the possibility to have a form not tied to an object (would not necessarily create or update an existing object), and perform other operations (like just send an e-mail or update multiple objects).

**Comment by ecino** [comment]
Here is a use case:

We have a page where we can donate for a fundraising project. The donation form would use a cms.form object. When someone donates, in the backend we try to:

1. Create or match the partner given its coordinates
2. Create invoice using the correct product for identifying the project and using the amount he entered in the form

This doesn't relate to an existing Odoo object, but it relates to res.partner and account.invoice. How would you handle this? In our first implementation, we didn't use main_object in the form, but we have several fields that we use and we inherit form_before, _form_create and form_after to produce our desired behaviour.

**Comment by simahawk** [comment]
> So that means a form should always relate to an object? It removes the possibility to have a form not tied to an object (would not necessarily create or update an existing object), and perform other operations (like just send an e-mail or update multiple objects).

Exactly the contrary: is NOT tied or related to an object. That's why it has been implemented like this. :)

You have an object, the main one IF you are creating or updating a specific model record (ie: a partner).

If your form has no model (no _form_model) then you put all the fields on the form and you do what you want w/ them. But you catch the values in `values` not in self.$fieldname.

Is there any piece of code I can see? Otherwise I'd be just guessing...

**Comment by ecino** [comment]
Ok, thanks for the explanations. I think the wrong thing I was doing is using self.field instead of using values. I will fix that in my implementation.
